---
- name: Configuration Template
  hosts: cisco
  gather_facts: true


  tasks:
  - ansible.builtin.template:
      src: templates/config.j2
      dest: ~/ansible/playbooks/lesson03/CFGS/{{inventory_hostname}}.txt
