---
- name: This playbook executes on cisco3 host
  hosts: cisco3
  gather_facts: true


  tasks:
    - name: This task prints the ansible_facts to stdout
      ansible.builtin.debug:
        var: ansible_facts


    - name:  This task prints ansible_facts. net_all_ipv4_addresses to stdout
      ansible.builtin.debug:
        var: ansible_facts.net_all_ipv4_addresses
